# Generated by Django 5.1 on 2024-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
