# Generated by Django 5.1 on 2024-08-31 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_photo_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
