# Generated by Django 5.1 on 2024-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_album_favorite_users_photo_favorite_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_public',
        ),
        migrations.AddField(
            model_name='album',
            name='access',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=50, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='photo',
            name='access',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=50, verbose_name='Доступ'),
        ),
    ]
